import numpy as np
import numpy as np
epsilons = range(2, 10, 2)
sigmas = np.arange(0.5, 1, 0.1)
clippings = np.arange(0.2, 1, 0.1)
g_batch_size =256
d_batch_size =256
lambda_gen = 1e-5
lambda_dis = 1e-5
lr_gen = 1e-5
num_microbatches=1
lr_dis = 1e-5
n_epoch =2
sigma = 0.5
label_smooth = 0.5
d_epoch = 5
g_epoch =10
n_emb = 128
l2_norm_clip=1.5
clip_coeff=1.5
pre_d_epoch = 0
pre_g_epoch = 0
neg_weight = [1, 1, 1, 1]
noise_multiplier=1
epsilon=200
type='test'
momentum=0.9
batches_per_lot=10
lot_size=batches_per_lot*d_batch_size
dataset = 'cora'
target_eps=range(0,200)
experiment = 'link_prediction'
train_file = '../data/%s/train_0.5' % dataset
test_file = '../data/%s/test_0.5' % dataset
train_file_new='/home/project/anaconda3/pycharm-community-2023.1.2/differentialprivacy_experimentation/differentialprivacy_experimentation/code/coratest.json'
pretrain_ckpt = ''
pretrain_dis_node_emb = []
pretrain_gen_node_emb = []
save = True
save_path = '/media/project/OS/monica/results/%s/%s/%s/%s/' % (experiment, dataset,epsilon,type)
save_last = True
verbose = 1
log = True
#n_node=24000
n_node=23166
delta=0.99
clipping_value=50